name: Run Tests

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    runs-on: gcp-k8s-vllm-l4-duo
    env:
        HF_TOKEN: ${{ secrets.HF_RED_HAT_READ_ONLY }}
    steps:
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - name: Install system dependencies
          run: |-
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends g++ gcc make
        - name: Set Env
          run: pip3 install --upgrade pip setuptools
        - name: "⚙️ Install dependencies"
          run: pip3 install .[dev] --extra-index-url https://download.pytorch.org/whl/cu129
        - name: clean up
          run: |
            echo "cleaning up disk space as GHA runner has limited disk size."
            python3 -m pip cache purge
            sudo rm -rf /usr/local/.ghcup
            sudo rm -rf /opt/hostedtoolcache/CodeQL
            sudo rm -rf /usr/local/lib/android/sdk/ndk
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /opt/ghc
            sudo rm -rf /usr/local/share/boost
            if [[ "$(cat /etc/issue)" =~ Ubuntu ]]; then
              sudo apt-get clean
            fi
            df -h
          shell: bash
        - name: "🔬 Running tests"
          run: make test
  python-tests-xpu:
    runs-on: intel-xpu-b60
    env:
        IMAGE_NAME: vllm-xpu-test:py312
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
        - name: Build docker image
          run: |-
            if [[ ! $(docker image ls --format '{{.Repository}}:{{.Tag}}' | grep -Fx "$IMAGE_NAME") ]]; then
              docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t $IMAGE_NAME -f .github/docker/Dockerfile.xpu .
            fi
            docker images | grep "vllm-xpu-test"
        - name: Set up docker container
          run: |-
            CONTAINER_NAME=vllm-test-container-${NODE_LABEL}
            if [[ $(docker ps -a --format '{{.Names}}' | grep -Fx "$CONTAINER_NAME") ]]; then
              docker rm -f $CONTAINER_NAME
            fi
            docker run -tid --disable-content-trust --privileged --name $CONTAINER_NAME -v ${{ github.workspace }}:/workspace -w /workspace $IMAGE_NAME
            echo "Show the container list after docker run ... "
            docker ps -a | grep "$CONTAINER_NAME"
            echo "CONTAINER_NAME=$CONTAINER_NAME" > $GITHUB_ENV
        - name: "⚙️ Install dependencies"
          run: |-
            docker exec  $CONTAINER_NAME \
              bash -c "uv pip install --upgrade pip setuptools && \
              uv pip install .[dev] --extra-index-url https://download.pytorch.org/whl/xpu"
        - name: "🔬 Running tests"
          run: |-
            docker exec -e NUMA_NODE=${NUMA_NODE} -e NUMA_CPUSET=${NUMA_CPUSET} -e ZE_AFFINITY_MASK=${ZE_AFFINITY_MASK} $CONTAINER_NAME \
              bash -c "cd tests && \
              numactl --physcpubind=${NUMA_CPUSET:-84-111} --membind=${NUMA_NODE:-3} pytest -c pytest-xpu.ini"
        - name: Clean up docker container
          run: docker rm -f $CONTAINER_NAME